 

DROP TABLE IF EXISTS order_activity; 

CREATE TABLE order_activity (
  order_activity_id    BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  warehouse_id BIGINT NOT NULL,
  number varchar(20) not null,
  transaction_group_id varchar(20) not null,
  activity_datetime DATETIME not null,
  username varchar(50) not null,
  rf_code varchar(50),
  type varchar(50) not null,
  outbound_order_id BIGINT,
  outbound_order_line_id BIGINT,
  pick_id BIGINT,
  short_allocation_id BIGINT,
  shipment_id BIGINT,
  shipment_line_id BIGINT,  
  quantity BIGINT,
  outbound_order_number varchar(50) ,
  outbound_order_line_number varchar(50) ,
  old_order_line_expected_quantity BIGINT,
  new_order_line_expected_quantity BIGINT,
  old_order_line_open_quantity BIGINT,
  new_order_line_open_quantity BIGINT,
  old_order_line_inprocess_quantity BIGINT,
  new_order_line_inprocess_quantity BIGINT,
  old_order_line_shipped_quantity BIGINT,
  new_order_line_shipped_quantity BIGINT,
  shipment_number varchar(50) ,
  shipment_line_number varchar(50),
  old_shipment_line_quantity BIGINT,
  new_shipment_line_quantity BIGINT,
  old_shipment_line_open_quantity BIGINT,
  new_shipment_line_open_quantity BIGINT,
  old_shipment_line_inprocess_quantity BIGINT,
  new_shipment_line_inprocess_quantity BIGINT,
  old_shipment_line_loaded_quantity BIGINT,
  new_shipment_line_loaded_quantity BIGINT,
  old_shipment_line_shipped_quantity BIGINT,
  new_shipment_line_shipped_quantity BIGINT,
  pick_number varchar(50),
  old_pick_quantity BIGINT,
  new_pick_quantity BIGINT,
  old_pick_picked_quantity BIGINT,
  new_pick_picked_quantity BIGINT,
  old_short_allocation_quantity BIGINT,
  new_short_allocation_quantity BIGINT,
  old_short_allocation_open_quantity BIGINT,
  new_short_allocation_open_quantity BIGINT,
  old_short_allocation_inprocess_quantity BIGINT,
  new_short_allocation_inprocess_quantity BIGINT,
  old_short_allocation_delivered_quantity BIGINT,
  new_short_allocation_delivered_quantity BIGINT,
  created_time DATETIME,
  created_by VARCHAR(50),
  last_modified_time DATETIME,
  last_modified_by VARCHAR(50)
);

