DROP TABLE if exists walmart_shipping_carton_label; 



CREATE TABLE walmart_shipping_carton_label (
  walmart_shipping_carton_label_id      BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  warehouse_id   BIGINT NOT NULL,   
  partner_id VARCHAR(100)  NOT NULL,
  doc_type VARCHAR(100)  NOT NULL,
  po_number VARCHAR(100)  NOT NULL,
  po_date VARCHAR(100)  NOT NULL,
  type VARCHAR(100) ,
  dept VARCHAR(100) ,
  vendor_id VARCHAR(100) ,
  ship_to VARCHAR(200) ,
  address_1 VARCHAR(300) ,
  city_state_zip VARCHAR(100) ,
  DC VARCHAR(100) ,
  GLN VARCHAR(100) ,
  item_number VARCHAR(100) ,
  WMIT VARCHAR(100) ,
  UPC VARCHAR(100) ,
  UK VARCHAR(100) ,
  GTIN14 VARCHAR(100) ,
  weight VARCHAR(100) ,
  description VARCHAR(100) ,
  order_quantity VARCHAR(100) ,
  UOM VARCHAR(100) ,
  piece_carton VARCHAR(100) ,
  carton_quantity VARCHAR(100) ,
  SSCC18 VARCHAR(100) ,
  ship_date VARCHAR(100) ,
  eta_date VARCHAR(100) ,
  SCAC VARCHAR(100) ,
  transportation_method VARCHAR(100) ,
  BOL VARCHAR(100) ,
  tracking_number VARCHAR(100) ,
  invoice_number VARCHAR(100) ,
  FOB VARCHAR(100) ,
  load_id VARCHAR(100) ,
  appointment_number VARCHAR(100) ,
  carrier_number VARCHAR(100) ,
  equipment_type VARCHAR(100) ,
  equipment_initial VARCHAR(100) ,
  equipment_number VARCHAR(100) ,
  seal_number VARCHAR(100) ,
  FOB_Mira VARCHAR(100) ,
  LOMA_COLTON_FAYETEVILLE VARCHAR(100) ,
  created_time DATETIME,
  created_by VARCHAR(50),
  last_modified_time DATETIME,
  last_modified_by VARCHAR(50));
 