 
ALTER TABLE inventory_snapshot_configuration ADD COLUMN inventory_snapshot_timing_1 INTEGER;
ALTER TABLE inventory_snapshot_configuration ADD COLUMN inventory_snapshot_timing_2 INTEGER;
ALTER TABLE inventory_snapshot_configuration ADD COLUMN inventory_snapshot_timing_3 INTEGER;
ALTER TABLE inventory_snapshot_configuration ADD COLUMN location_utilization_snapshot_timing_1 INTEGER;
ALTER TABLE inventory_snapshot_configuration ADD COLUMN location_utilization_snapshot_timing_2 INTEGER;
ALTER TABLE inventory_snapshot_configuration ADD COLUMN location_utilization_snapshot_timing_3 INTEGER;
ALTER TABLE inventory_snapshot_configuration ADD COLUMN inventory_aging_snapshot_timing_1 INTEGER;
ALTER TABLE inventory_snapshot_configuration ADD COLUMN inventory_aging_snapshot_timing_2 INTEGER;
ALTER TABLE inventory_snapshot_configuration ADD COLUMN inventory_aging_snapshot_timing_3 INTEGER;